source $HOME/.config/vim/pluglist/plugins.vim
source $HOME/.config/vim/plugconf/coc.vim

let mapleader=","

syntax on
filetype on
colorscheme zellner

let g:netrw_dirhistmax=0
let g:multi_cursor_exit_from_insert_mode=1
let g:multi_cursor_exit_from_visual_mode=1
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_quit_key='<esc>'

set nocp nu rnu hls ic is
set autoindent
set nobackup
set nowritebackup
set noswapfile
"set viminfo+=n~/.config/vim/viminfo
set viminfo+='1000,n~/.config/vim/viminfo
set laststatus=2

set backspace=indent,eol,start
set clipboard=unnamed,unnamedplus

" replace tabs with 3 spaces
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" H/M/L screen and begin/end of line
nnoremap H 0
nnoremap L $

" map escape key to jk 
inoremap <silent> jk <esc>
inoremap <silent> JK <esc>
vnoremap <silent> jk <esc>
vnoremap <silent> JK <esc>

" go to next custom <++> marker
nnoremap <leader>l <esc>/<++><cr>c4l
inoremap <silent> <leader>l <esc>/<++><cr>c4l

" next and previous tab navigation
nnoremap <silent> <leader>z :tabp<cr>
nnoremap <silent> <leader>x :tabn<cr>

" next previous split navigation
nnoremap <C-h> <c-w>h
nnoremap <C-j> <c-w>j
nnoremap <C-k> <c-w>k
nnoremap <C-l> <c-w>l

" next and previous paragraph navigation
nnoremap ] }
nnoremap [ {
vnoremap ] }
vnoremap [ {

" map console mode to semi-colon
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

" inserting codeblock brackets {} to functions
nnoremap <leader>. o{<cr>}<++><esc>ko
inoremap <leader>. <esc>o{<cr>}<++><esc>ko
nnoremap <leader>/ A{<cr>}<++><esc>ko
inoremap <leader>/ <esc>A{<cr>}<++><esc>ko

" inserting date and time for journal =
nnoremap <leader>d :read !echo "[ `date '+\%a \%Y-\%m-\%d'` ]"<cr>
nnoremap <leader>t :read !echo "`date '+\%H:\%M'` - "<cr>
inoremap ;d <esc>:read !echo "[ `date '+\%a \%Y-\%m-\%d'` ]"<cr>
inoremap ;t <esc>:read !echo "`date '+\%H:\%M'` - "<cr>

" file manipulation (create, read, update, delete)
nnoremap <leader>w :w<cr>
nnoremap <leader>q :q<cr>
nnoremap <leader>e :q!<cr>

" vimrc manipulation (edit, source, buffer nav, compiler)
nnoremap <leader>v :edit $MYVIMRC<cr>
nnoremap <leader>s :source $MYVIMRC<cr>
nnoremap <leader>n :bprev<cr>
nnoremap <leader>m :bnext<cr>
nnoremap <silent> <leader>c :!compiler <C-r>%<cr>
"nnoremap <silent> <leader>c :!xelatex main<cr>

" language specific key maps for Latex and C++
source $HOME/.config/vim/mappings/keymaps.vim
